// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Divas-Gupta30/medium-blogs/wire-go/service"
)

// Injectors from wire.go:

func InitialiseNotificationService(conf1 *service.DbConf, conf2 *service.Config) *service.NotificationService {
	db := service.NewDb(conf2)
	smtpClient := service.NewSMTPClient(conf2)
	emailService := service.NewEmailService(smtpClient)
	notificationService := service.NewNotificationService(db, emailService)
	return notificationService
}
